### ISSUE TITLE
Query logic seems bugged

### ISSUE THREAD

**Issue by larssn** [adriancarriger/angularfire2-offline#32]
So we've been switching out `FirebaseListObservable` with the `Afo` variant.

This has broken the following pretty simply method below.
Before the method DID NOT return sessions that were "completed", but now it does.

Is there something I'm misunderstanding? Could it be getting a cached value? :-)

```
getCompleted() {
        return this.afoDb.list(`/sessions`, {
            query: {
                orderByChild: 'completed',
                equalTo: true,
                limitToLast: 8
            }
        });
    }
```

Switching back to `FirebaseListObservable` makes the query work as expected again.

**Comment by adriancarriger** [comment]
Hi @larssn, yes, it definitely sounds like an issue with the cached value, and this may be a duplicate of issue #9.

If the value is loaded directly from Firebase (skipping the local cache) the query will work, otherwise it will fail. I've made some progress with this on the [query-support-3 branch](https://github.com/adriancarriger/angularfire2-offline/tree/query-support-3) and hope to finish it soon.

Please let me know if this sounds different from issue #9. Thanks!

**Comment by larssn** [comment]
Its probably related, I'll close this as one topic should be enough.

Sorry for not noticing the existing issue!
