### ISSUE TITLE
Observing single value in DB: No update on change

### ISSUE THREAD

**Issue by JaneDawson** [adriancarriger/angularfire2-offline#45]
When I subscribe to a single value in my Firebase DB, the observable doesn't trigger when the value changes.

In the following example the "balance" node is of type "Number".

```
getBalanceStream(userId){
    this.db.object('/users/'+userId+'/balance').subscribe( bal=> {
      this.balance= bal.$value;
    }
  }
```
When the user's balance changes in the database, the arrow function is not triggered. `this.balance` doesn't get updated.

When I use regular AngularFire2 it works as expected.

**Comment by adriancarriger** [comment]
I've been able to reproduce your issue [here](https://github.com/adriancarriger/angularfire2-offline/blob/gh-pages/issues/45.1/src/app/app.component.ts) with a [demo](https://adriancarriger.github.io/angularfire2-offline/issues/45.1/dist/).

If you click the button, the data is saved and written to Firebase, but it is not displayed in the ui.

I'll be working on this one. Thanks for posting!

**Comment by JaneDawson** [comment]
Thank you! I appreciate that.

**Comment by adriancarriger** [comment]
This should be fixed in version 4.1.5 ..let me know if you still experience any issues. Thanks!

**Comment by JaneDawson** [comment]
Thank you for updating. I just tested it. Unfortunately it's still the same as before. Subscribing to a single value doesn't work.

**Comment by adriancarriger** [comment]
Hi @JaneDawson, here's a [working demo](https://adriancarriger.github.io/angularfire2-offline/issues/45.2/dist/) ([source code](https://github.com/adriancarriger/angularfire2-offline/tree/gh-pages/issues/45.2)) using angularfire2-offline version 4.1.5

When I was making the demo my package.json had `"angularfire2-offline": "^4.1.5"` which resolved to version 4.2.0 (a version that was published unintentionally). [By changing](https://github.com/adriancarriger/angularfire2-offline/commit/82b8e98b8902120a168bc0eaac23b7dc54cba7d9#diff-558f2c6a52570b01181c3963d31bd9e7R27) the package.json to `"angularfire2-offline": "4.1.5"` the issue was fixed.

You can check which version your app is running by going to: 

`your-project/node_modules/angularfire2-offline/package.json`

Let me know if this solves your issue. Thanks!

**Comment by JaneDawson** [comment]
That fixed it for me, as well. Works just fine now.
Thank you, @adriancarriger. I appreciate it!

**Comment by adriancarriger** [comment]
Awesome, glad it's working now! 👍

**Comment by JaneDawson** [comment]
Unfortunately, I have to reopen this issue.
Everything works fine, except if the value of the subscribed attribute is 0.

If in the following example the account balance object `..users/'userId'/balance'` is 0 in the database, then `bal.$value` becomes `undefined`. This shouldn't be, since 0 is a valid value for the balance.
```
getBalanceStream(userId){
    this.db.object('/users/'+userId+'/balance').subscribe( bal=> {
      this.balance= bal.$value;
    }
  }
```

**Comment by JaneDawson** [comment]
Anything new here?

**Comment by adriancarriger** [comment]
Hi @JaneDawson, thanks for reopening! I'll be looking into this!

**Comment by adriancarriger** [comment]
I can confirm this issue and have made a [demo](https://adriancarriger.github.io/angularfire2-offline/issues/45.3/dist/) (with [code](https://github.com/adriancarriger/angularfire2-offline/blob/gh-pages/issues/45.3/src/app/app.component.ts)). When the counter gets to zero no number is shown, however the value in the database is zero. I'll be working fixing this!

**Comment by JaneDawson** [comment]
Thank you. I appreciate that. Works well now!

**Comment by adriancarriger** [comment]
Awesome, glad it's working! 👍
