### ISSUE TITLE
Initialize with local data?

### ISSUE THREAD

**Issue by pwespi** [adriancarriger/angularfire2-offline#49]
Great package. I really appreciate your work!

Is there a way to initialize the localForage data with a local JSON file, such that when the app is opened for the first time while offline, there is already some data? I'm talking about an Ionic app on a smartphone, where I would like to ship the data as a JSON file with the app bundle and only use firebase for incremental updates.

**Comment by adriancarriger** [comment]
Hi @pwespi, I think you've come across a very important use case! 👍

## Demo

Here is [a demo](https://adriancarriger.github.io/angularfire2-offline/issues/49.1/dist/) (with [code](https://github.com/adriancarriger/angularfire2-offline/blob/gh-pages/issues/49.1/src/app/app.component.ts#L28-L35)) of initializing app data from a [Json file](https://github.com/adriancarriger/angularfire2-offline/blob/gh-pages/issues/49.1/src/app/json-file-example.json), and it does work offline! 🎉 
### Testing in browser

1. [Visit demo](https://adriancarriger.github.io/angularfire2-offline/issues/49.1/dist/)
1. Go offline
1. Open dev tools, go to IndexedDB, click `localforage`, then click `keyvaluepairs`, and clear the browser's local storage by clicking the lower righthand button <img width="521" alt="screen shot 2017-07-30 at 7 53 44 am" src="https://user-images.githubusercontent.com/7516020/28753592-5620f980-74fc-11e7-942e-871b14188b78.png">
1. Reload demo

You should now see data initialized from the [Json file](https://github.com/adriancarriger/angularfire2-offline/blob/gh-pages/issues/49.1/src/app/json-file-example.json)!

## Loading Json files

Loading Json files can be a little tricky using Typescript.

I just added the following to [src/typings.d.ts](https://github.com/adriancarriger/angularfire2-offline/blob/gh-pages/issues/49.1/src/typings.d.ts#L6-L9):

```ts
declare module "*.json" {
  const value: any;
  export default value;
}
```

and [imported it](https://github.com/adriancarriger/angularfire2-offline/blob/gh-pages/issues/49.1/src/app/app.component.ts#L3) like this:

```ts
import jsonFile from './json-file-example.json';
```

These links may be helpful:

* [Hackernoon - How to Import json into TypeScript](https://hackernoon.com/import-json-into-typescript-8d465beded79)
* [SO - how to use a json file in a typescript file](https://stackoverflow.com/questions/41372187/how-to-use-a-json-file-in-a-typescript-file)

## Initializing data

To initialize data, just add the data as you normally would with any Firebase list/object.

### [Example](https://github.com/adriancarriger/angularfire2-offline/blob/gh-pages/issues/49.1/src/app/app.component.ts#L28-L36):

```ts
initializeData() {
  // Add list data from Json file
  this.groceries.remove(); // Remove is optional
  jsonFile.listExample.forEach(listItem => {
    this.groceries.push(listItem);
  });
  // Add object data from Json file
  this.car.set(jsonFile.objectExample);
}
```

Just call the `initializeData` method when you want to initialize your app's data.

## Next steps

Next you might want to make sure that the data was not already initialized by adding a data object to your Firebase database. You would then check this data point before initializing data so that the Json file is only loaded once.
