### ISSUE TITLE
Promises filing twice

### ISSUE THREAD

**Issue by wbhob** [adriancarriger/angularfire2-offline#53]
When in airplane mode, the app fires the regular promise and the offline promise simultaneously. This is bad because I have no way of checking whether or not they're online, and the promise should fire only once.

FB.push().offline.then and FB.push().then

**Comment by adriancarriger** [comment]
Hi @wbhob, from what I understand that is currently the expected behavior. Here's what the two promises do:

* **Regular promise** - the regular `promise` will complete after the write has been made to Firebase
* **Offline promise** - the offline `promise.offline` will complete after a write to the local device has been made. This let's you know that if you refresh/close your app at this point that the data is stored on the device. When the device gains access to the internet again, it will try to write the data to Firebase.

## Why they finish simultaneously

You've noticed that they finish at about the same time. This is because as soon as a write is made Afo will both send the data to Firebase and write the data locally to the device. They often both happen so fast that it appears to happen at the same time.

## Example

If you take your app offline, you'll notice that only the offline promise will complete. If you then go back online without a refresh you'll see the regular Firebase promise complete.

## Offline presence

Afo doesn't help with managing online/offline presence, but luckly [Firebase does](https://firebase.google.com/docs/database/web/offline-capabilities)

Let me know if I can help out! Thanks 👍

**Comment by wbhob** [comment]
Right, I understand this, however, the issue is that I need to either persist to the database, or persist it locally. In a real-world use case, there should be a promise that resolves once depending on the current state of the app. 

Immediately after writing this, I realized that I was calling push() twice... closing. I will make a PR with some new info regarding promises.

**Comment by adriancarriger** [comment]
@wbhob thanks for the PR!
