### ISSUE TITLE
Offline cache didn't work firebase images (storage)

### ISSUE THREAD

**Issue by mumairofficial** [adriancarriger/angularfire2-offline#75]
I was wondering if this plugin supports the firebase storage images. 
I have stored images on firebase storage bucket which I download via link embedded in database records, is there any way to handle this scenario

**Comment by larssn** [comment]
It doesn't support it.

But your best bet would be to enable caching headers for firebase storage.
Check out: https://firebase.google.com/docs/reference/js/firebase.storage.SettableMetadata#cacheControl

It would offload the caching responsibility to the webview. Not sure if it would work in a pure offline sense (try it), but we're using it in a chat-app to get images to simply load faster, because they don't have to be redownloaded.

**Comment by rtm** [comment]
One immediately thinks of trying to use service workers, but unfortunately they don't seem to play well with Cordova, which is my environment.
