### ISSUE TITLE
firebase.promise<void>  Error

### ISSUE THREAD

**Issue by quiksa** [adriancarriger/angularfire2-offline#78]
Hello, I am having problems with firebase.promise<void> after updating my npm packages 

this is the error
Namespace 'firebase' has no exported member 'Promise'.

Does anyone have any solution?

**Comment by ntbnnt** [comment]
I think the project needs updated support AngularFire2 5.x which had some breaking changes from AngularFire 4.x - older firebase interfaces and code appears to have been moved to the database/deprecated and this package probably needs updated to support that or the new stuff in database. I switched to using AngularFire 5.0.0-rc3 with FireStore's offline featureset because it fit my needs until (hopefully) this package can be updated.

If you lock your AngularFire2 version to 4.0.0-rc0 this package should still be able to be used as that was the case in one of my projects that depend on this one.

**Comment by oky1** [comment]
Namespace 'firebase' has no exported member 'Promise'.
Please update ... to v5

**Comment by Bottley** [comment]
Any news on an update to Af2 v5? Or are there in patches or workarounds recommended in the meantime?

**Comment by mrameezraja** [comment]
My packages:
```json
"dependencies": {
    "@ng-bootstrap/ng-bootstrap": "^1.0.0-beta.9",
    "angularfire2": "^5.0.0-rc.4",
    "angularfire2-offline": "^4.3.1",
    "firebase": "^4.8.2"
  },
```
but still having same issue.

**Comment by anil1712** [comment]
I am also getting the same? Is anyone got some solution for the same?

**Comment by adriancarriger** [comment]
Closing in favor of #89
